# -*- coding: utf-8 -*-
"""DigitRecCNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScZfevZa4j2eaOctmwfpLx0rG1oOU5Wu
"""

import pandas as pd

df = pd.read_csv('/content/train.csv')
df.head()

df.shape

y = df['label']
X = df.drop('label',axis=1)/255

X = X.values.reshape(42000,28,28,1)
X.shape

from tensorflow.keras.utils import to_categorical
ya = to_categorical(y,num_classes=10)
ya

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten

model = Sequential()
model.add(Conv2D(16,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D())
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D())
model.add(Flatten())
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy', metrics = ['accuracy'])
model.fit(X,ya,epochs=30,batch_size=64)

model.summary()

import cv2,os

def predict_digit(file):
    A = cv2.imread(file,0)
    A = cv2.resize(A,(28,28))
    A = A/255
    A = A.reshape(1,28,28,1)
    yp = model.predict_on_batch(A)
    return int(yp.argmax())

files = ['0.png', '1.png', '2.png','3.png', '4.png', '5.png',
         '6.png', '7.png', '8.png', '9.png', '1 1.png','88.png']

# Test each one
for f in files:
    prediction = predict_digit(f)
    print(f"{f} → {prediction}")

